### DISCUSSION TITLE
Russian Language Leader

### DISCUSSION THREAD

**Discussion by synesthesiam** [OHF-Voice/intents#1074] [Language Leaders]
@HepoH3 when you get a chance, could you please look into translating the `HassGetState` sentences/responses?

**Comment by HepoH3** [comment]
Yup, gonna check it in a few minutes.

**Reply by synesthesiam** [reply]
Thanks!

**Comment by HepoH3** [comment]
So I spend a few hours in order to make things work and failed. I'm not sure it will work with current state of things. Just look at my common.yaml:

```yaml
#...
  cover_states:
    values:
      - in: "не[ ]задернут[а[я]|ы[е]]|открыт[а|ы[е]]|поднят[а|ы[е]]"
        out: "open"
      - in: "задернут[а[я]|ы[е]]|открыт[а|ы[е]]|поднят[а|ы[е]]"
        out: "closed"
#...
```

And while it can have one state case in one sentence, it can have another state case with the same object in another sentence/response, while it will have third state case in state attribute. And you need to pick correct one for the response.
For now tests are so failed, that I can't make things work even with dirty workarounds in fixtures, or if I simplify sentence patterns in tests to troglodyte level.

Maybe I misunderstand something. I can read ukrainian, it quite close to russian, so if it'll have GetState support, I think I will be able to port these support into russian.
