### DISCUSSION TITLE
Sensor intents

### DISCUSSION THREAD

**Discussion by spuljko** [OHF-Voice/intents#1204] [_Q&A]
I am trying to write sentences for specific device class sensors, like "What is the pool temperature", "What is the living room air quality", "How much energy am I using?"
Now I am stuck with getting sensor values for specific area, like "What is the humidity in the living room?", but recognition fails for that.
Is that even possible or am I doing something wrong? You can check my changes [here](https://github.com/home-assistant/intents/compare/main...spuljko:intents:sensors_en).

**Comment by nikito7** [comment]
Aliases in HA

**Reply by spuljko** [reply]
That doesn't answers my question

**Comment by TheFes** [comment]
which error do you get when running the tests?

**Reply by spuljko** [reply]
Recognition failed for XXX. None is not None,
common.yaml
```
  sensor_classes:
    values:
      - in: "[air] humidity [level]|humity in [the] air"
        out: "humidity"
```

sentences.yaml:
```
      - sentences:
          - "([can you] tell me|what is) [the] {sensor_classes:device_class} [like] [in] [of] [the] (<name>|<area>)"
        requires_context:
          domain: "sensor"
          device_class:
            - "humidity"
        response: "sensor_measure_state"
```

_fixtures.yaml
```
  - name: "AQ Sensor"
    id: "sensor.humidity_aq"
    area: living_room
    state: "60"
    attributes:
      device_class: "humidity"
```

tests.yaml
```
  - sentences:
      - "What is the humidity in the living room?"
    intent:
      name: HassGetState
      slots:
        area: "Living Room"
        device_class: "humidity"
    response: "60 %"

```
What is the humidity of the AQ Sensor? - that works ok (single entity state)
What is the humidity in the living room? - not working.
