### DISCUSSION TITLE
Device-related queries ("what is the <attribute> of <device>?")

### DISCUSSION THREAD

**Discussion by tetele** [OHF-Voice/intents#1401] [_Ideas]
At the moment you can only name entities in queries you perform.

Does anybody think it's a good idea to allow queries for sensor entities based on the device they belong to? For example, let's say I have a smart plug named "Washing machine plug". It exposes entities such as:
- Washing machine plug power
- Washing machine plug energy consumption
- Washing machine plug device temperature

If I wanted to learn about those, I'd have to say "what is the Washing machine plug device temperature?" for instance.

But what if I could say "what's the temperature of the washing machine plug?" (hint: `device_class: temperature`) or "how much power does the washing machine plug draw?" (hint: `device_class: power`).

```
language: en
intents:
  HassGetState:
    data:
      - sentences:
          - "<what_is> the temperature of [the] {device_name}"
        response: one
        requires_context:
          domain: sensor
          device_class: temperature
        slots:
          domain: sensor
          device_class: temperature
      - sentences:
          - "how much power (does {device_name} (draw|use)|is {device_name} (drawing|using))"
        response: one
        requires_context:
          domain: sensor
          device_class: power
        slots:
          domain: sensor
          device_class: power
```

Is that useful?
