### DISCUSSION TITLE
Custom Intent for Doors and Windows Monitored by Binary Sensors

### DISCUSSION THREAD

**Discussion by OzGav** [OHF-Voice/intents#1502] [_Show and tell]
As per here https://github.com/home-assistant/intents/issues/1216 asking Assist for the state of windows and doors which are actually binary sensors is not currently supported. Since I have no covers I thought I would write some custom intents to fix this. 

```
conversation:
  intents:
    howmanywindowsopen:
      - "How many windows are open"

    howmanydoorsopen:
      - "How many doors are open"

    whichdoorsopen:
      - "Which doors are open"

    whichwindowsopen:
      - "Which windows are open"

intent_script:
  howmanywindowsopen:
    speech:
      text: "{{ states.binary_sensor | selectattr('attributes.device_class', 'defined') | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | list | count }}"

  howmanydoorsopen:
    speech:
      text: "{{ states.binary_sensor | selectattr('attributes.device_class', 'defined') | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | list | count }}"

  whichdoorsopen:
    speech:
      text: "{% if states.binary_sensor | selectattr('attributes.device_class', 'defined') | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | map(attribute='name') | list | count > 0 %}
          {{ states.binary_sensor | selectattr('attributes.device_class', 'defined') | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | map(attribute='name') | list | join (' and ')  }}
        {% else %}
          None
        {% endif %} "

  whichwindowsopen:
    speech:
      text: "{% if states.binary_sensor | selectattr('attributes.device_class', 'defined') | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | map(attribute='name') | list | count > 0 %}
          {{ states.binary_sensor | selectattr('attributes.device_class', 'defined') | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | map(attribute='name') | list | join (' and ')  }}
        {% else %}
          None
        {% endif %} "
```
