### DISCUSSION TITLE
Idea to improve the impact of our work as language leaders

### DISCUSSION THREAD

**Discussion by jlpouffier** [OHF-Voice/intents#1889] [_General]
Morning @home-assistant/language-leaders !
_(I'm JLo, I work at Nabu Casa as product manager for Home Assistant)_

I am currently thinking about a solution with @matthiasdebaat and would like your feedback before going further.

## Problem(s)
I'll present two problems, only one of these is focused on Language leaders but the solution I'll explain further down solves both
- As a user, I do not know what to do when Assist fails to understand my intent
- As a language leader, I do not know what sentences are missing, and where my users struggle 

## Solution
The first problem is partly solved with our better error handling that will soon be available in the next release of home assistant.
This:
```yaml
    no_intent: "Sorry, I couldn't understand that"
    no_area: "Sorry, I am not aware of any area called {{ area }}"
    no_domain: "Sorry, I am not aware of any {{ domain }} in the {{ area }} area"
    no_device_class: "Sorry, I am not aware of any {{ device_class }} in the {{ area }} area"
    no_entity: "Sorry, I am not aware of any device or entity called {{ entity }}"
    handle_error: "An unexpected error occurred while handling the intent"
```
This means that a user will have bits of context about how to solve a particular issue.

A dummy example: 
If you say "_Turn off the lights in the bathroom_" and assist replies "_Sorry, I am not aware of any lights in the bathroom area_", it's a clue on how to solve this: You need to assign lights in the bathroom area.
It's already a great start.

I am thinking about going one step further:

I'd like to provide a summary of all the sentences that failed on a user system _(Somewhere ... We don't know where yet, we are brainstorming with @matthiasdebaat)_

This list of unmatched sentences would be split into two parts:

### Solvable by the user
Here the idea is pretty simple, it's to create resolutions flows tailored to a specific error that can be solved directly by the user.

A few examples to illustrate:
- You said "Turn off the lights in the `spaceship`", but I do not know any area called `spaceship`
  - Resolution flow: Here are your areas, pick one and I will add `spaceship` as an alias
- You said "Open the `curtains` in the `living room`", I am aware of the `living room` area and you do have `curtains` ... but none of them are assigned to the `living room`
  - Resolution flow: Here are your `curtains`, pick the ones you want to assign to the `living room` area and I'll do it. 

### Not solvable by the user
This is the part where I need your feedback.
I see all the sentences said by our users that currently do not match any intent as very actionable data.
And I would like to use this data in a way.

Of course, while keeping the privacy DNA in mind, we cannot just "push" this data somewhere without user consent - That's not us.

What I am thinking about is to 
- List all sentences that a user said that we failed to match
- Provide a **simple button to push this sentence to the relevant language leader** so he/she is aware that a user expects this sentence to work

Pretty simple.

We'll need to be pretty clear in the wording and UX behind this button, I don't see this button as a "Report bug" that requires a fix at some point in time.
I see it more as a data point that a user I willing to share with you: "I was expecting this sentence to work, and it does not" (End of the story)

**Pros**
- You'll get clear signals of what's not working in your language. Some of these sentences will be able to be added to current intent (like a missing common sentence to turn on a light in dutch that the leader just did not think about)
- We (all of us) will get clear signals on the most important missing intents (Clean a room? Set the position of a cover? Who knows today ... )

**Cons**
- Spam spam spam. We need to find a solution that does not spam you. I'd like to avoid having one GitHub issue per button click, I'd like to find a way to consolidate this into a table somewhere so that you can act on it at your own pace.
- Non-actionnalbe data, I foresee a lot of failed intents due to mismatched speech-to-text (A very common one is "Closed the garage door" instead of "Close the garage door") 

What do you think?

Would you like to know to top 10 failing sentences in your language to work on them?
Do you think the solution solves the problem?
Feel free to discuss here ☺️

Thanks a lot!

JLo
