### DISCUSSION TITLE
Support for Chinese Simplified Language

### DISCUSSION THREAD

**Discussion by Kgym-Hina** [OHF-Voice/intents#416] [Supported Sentences]
I would like to be a volunteer.

**Comment by jjcszxh** [comment]
would like to be a volunteer.

**Comment by synesthesiam** [comment]
Thanks! I've added empty `zh` templates: https://github.com/home-assistant/intents/tree/main/sentences/zh
Please start with `_common.yaml` and the `homeassistant_*.yaml` files.

Did I get the correct native name for Simplified Chinese? 中文

**Comment by al-one** [comment]
- https://github.com/al-one/home-assistant-intents/commit/154a94e95d72d234c5f69697274a3ea722057fdb

I'm contributing sentences for Chinese and have a little problem.
In Chinese, `打开` is used for both `turn on` light and `open` curtain, which makes one intent match multiple sentences.
See the example below:
```yaml
# sentences/zh/cover_HassOpenCover.yaml
language: zh
intents:
  HassOpenCover:
    data:
      - sentences:
          - "打开 [<area>] <name>"
        slots:
          name: all
      - sentences:
          - "打开车库门"
        slots:
          device_class: garage_door
      - sentences:
          - "打开 [<area>] 窗帘"
        slots:
          device_class:
            - blind
            - curtain
            - shutter
```
```yaml
# sentences/zh/fan_HassTurnOn.yaml
language: zh
intents:
  HassTurnOn:
    data:
      - sentences:
          - "打开 [<area>] (<name> | 风扇)"
        slots:
          domain: fan
```
```yaml
# tests/zh/cover_HassOpenCover.yaml
language: zh
tests:
  - sentences:
      - "打开左侧窗帘"
    intent:
      name: HassOpenCover
      slots:
        domain: cover
        name: cover.curtain_left
```
```
E               AssertionError: For '打开左侧窗帘' expected intent HassOpenCover, got HassTurnOn
E               assert 'HassTurnOn' == 'HassOpenCover'
E                 - HassOpenCover
E                 + HassTurnOn
tests/test_language_sentences.py:53: AssertionError
```
