### DISCUSSION TITLE
Slovak sentences that should be supported / Návrhy na Slovenské frázy

### DISCUSSION THREAD

**Discussion by LubosKadasi** [OHF-Voice/intents#480] [Supported Sentences]
Discussion on the suggestions of phrases for controlling the home assistant by voice in the Slovak language.

**[SK]** Diskusia o návrhoch fráz pre ovládanie home assistant hlasom v Slovenskom jazyku.

Current state: **[SK]** Aktuálny stav https://ohf-voice.github.io/intents/

**Comment by rici44** [comment]
Nie som v Github doma, učím sa. Prešiel som [Readme.md](https://github.com/home-assistant/intents). [Codespace](https://github.com/home-assistant/intents/blob/main/docs/codespace/README.md) vytvorí každý samostatne alebo bude jedno pre sk jazyk?

**Reply by LubosKadasi** [reply]
Ahoj @rici44 , to je dobrá otázka. Asi samostatne a hlavne si aktualizovať branch.
Práve teraz som to riešil: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui

**Reply by stevoh6** [reply]
Najlepsie je  sa drzat blizko "git-flow" logiky. To znamena, ze ak idem robit zmeny spravim nasledovne kroky:
1. updatnem si master branchu
2. vytvorim si feature branchu 
3. robim zmeny vo feature branchy a komitnem ich
4. vytvorim pull request "feature brancha do mastra"

**Comment by stevoh6** [comment]
Keby nieco potrebujete pomoct s prekladom alebo  aj ohladom gitu/ha pingnite ma  (kontakty mam v profile) :-) 
Pozrel som si preklady, vyzera to super :-)

**Reply by LubosKadasi** [reply]
Ahoj @stevoh6 ak máš chuť a čas, tak ešte chýba komplet fan domain. Preklady aj testy https://github.com/home-assistant/intents/blob/main/sentences/sk/fan_HassTurnOn.yaml

**Reply by schizza** [reply]
@LubosKadasi pokud chcete, máme vše přeložené do cs, stačí upravit do sk (asi bych to zvládl), ale nechce s mi do toho úplně montovat, když nejsem rodilý SK 👯 
https://github.com/home-assistant/intents/tree/main/sentences/cs

**Reply by stevoh6** [reply]
ja si nato najdem nedelu cas :) az dnes som si vsimol koment :/

**Reply by stevoh6** [reply]
Preklady pridane, aj na responses.  Skusim popridavat aj viac odpovedi podla typu otazky, prikazu.
Musim napr nastudovat ci a ako sa da pridat rychlost na "ventilator". 

https://github.com/home-assistant/intents/pull/731

**Reply by LubosKadasi** [reply]
@stevoh6 veľká vďaka. Pozrel a testol som zmeny. PR som nestihol dopozerať a už to @schizza vyriešil. 
Dobrá práca. 
Vďaka Páni.

**Reply by schizza** [reply]
@LubosKadasi Ještě bych upravil další věci, ale jak jsem už psal - nejsem si úplně 100% jistý významem - hlavně množné/jednotné číslo. 
Ale třeba i u světel bych určitě rozdělil světla na - jednotlivá světla - která by měla svoje `sentences` a hromadné dotazy na `area`. - Jestli chápeš, jak to myslím. Protože pak se musí v odpovědi samozřejmě zohlednit `{{ slot.name }} a {{ slot.area }}`. Tak aby ty odpovědi dávaly smysl.
Příklad je teď u větráků, které jsem revidoval. Byl ta velký mišmaš :)

```
 - sentences:
      - "vypni všetky svetlá v kuchyni"
      - "vypni svetlá v kuchyni"
      - "vypni osvetlenie v kuchyni". - předpokládám, že tady je to množné č.
      - "vypni svetlo v kuchyni"  -  tato věta by měla mít svůj vlastní slot v sentences - adresujeme jednu entitu {name} ne {area}
      - "zahas všetky svetlá v kuchyni"
      - "zahas svetlá v kuchyni"
      - "zahas osvetlenie v kuchyni"
      - "zahas svetlo v kuchyni". - stejně tak do slotu s předchozím komentem
      - "zhasni všetky svetlá v kuchyni"
      - "zhasni svetlá v kuchyni"
      - "zhasni osvetlenie v kuchyni"
      - "zhasni svetlo v kuchyni".              -- dtto
```

Snad je to pochopitelně napsaný 😄

**Reply by stevoh6** [reply]
Jo to mozem kuknut/spravit neskor tento tyzden ked sa k tomu dostanem v dalsom pull requeste ;)

**Reply by LubosKadasi** [reply]
@schizza vďaka, asi rozumiem. 
Myslíš napríklad "Zhasni 'stropné svetlo' v 'kuchyni'" a "Zhasni 'kuchynský luster'"?

p.s.: spravil som menší pr s fixami. https://github.com/home-assistant/intents/pull/757/files - testy prešli

**Comment by Pheggas** [comment]
Čaute. V TurnOn sekcií som si všimol že nie je <turn_on> {name} [v|vo|na|pred|za|pod|pred] {area}. Je to možný dôvod prečo nefunguje veta ako: "zapni zásuvka v detská"? Kde "zásuvka" je smart zásuvka ako alias ku zariadeniu, a "detská" je izba / oblasť?

PS: v angličtine to ide - "Turn on plug in detská" (kde "plug" je druhý alias ku rovnakému zariadeniu)

![image](https://github.com/home-assistant/intents/assets/9994511/d22b67af-da3d-4713-948e-3670e258969d)

**Update:**
Aktualizoval som Hassio na latest verziu (mal som nejakú minuloročnú) a pre zmenu mi to hádže že nevie nájsť oblasť:
![image](https://github.com/home-assistant/intents/assets/9994511/d98b7d93-948b-4c6e-90eb-17c8ca215e30)

**Reply by LubosKadasi** [reply]
Ahoj, pozriem sa na to. Viem, že keď sa to implementovalo, tak tam bol nejaký problém. Už si ale nepamätám aký.
Skúsim to podľa en https://github.com/home-assistant/intents/commit/e623f667b5079a91a52b012228fdd790a828256d 

**Hotfix:** Aktuálne by malo pomôcť pridať alias pre "plug": "plug v detská"

**Reply by Pheggas** [reply]
Áno to by pomohlo. Mne len išlo o pointu a či ten systém chápem správne. 

Len side question. Dá sa pridať alias aj na oblasť? aby som mohol zadať príkaz hlasovo a mohol to aj vyskloňovať? Prípadne plánuje sa nejaký skloňovací update pre hassio commandy?

**Reply by LubosKadasi** [reply]
Pokiaľ viem, tak áno dá sa pridať alias aj na area [https://www.home-assistant.io/voice_control/aliases](https://www.home-assistant.io/voice_control/aliases/)

Čo sa týka update: V podstate to riešia aliasy. Pokiaľ viem, tak sa to diskutuje ale je to komplikovanejšie (názvy, miesta, čisla) ako by sa zdalo. Najmä ak by to malo byť univerzálne pre všetky podporované jazyky.

**Reply by Pheggas** [reply]
Diky za info. Rád by som contributoval čo sa týka slovenčiny napríklad aj takýmto štýlom - podpora skloňovania. Ale ak to je len v štádiu diskusie tak zatiaľ asi nemám ako prispieť.

**Reply by LubosKadasi** [reply]
> Diky za info. Rád by som contributoval čo sa týka slovenčiny napríklad aj takýmto štýlom - podpora skloňovania. Ale ak to je len v štádiu diskusie tak zatiaľ asi nemám ako prispieť.

Ahoj, 

smelo do toho:

Vety: https://developers.home-assistant.io/docs/voice/intent-recognition/contributing
Hlas: https://developers.home-assistant.io/docs/voice/contributing-your-voice 
Language leaders: https://developers.home-assistant.io/docs/voice/language-leaders

**Reply by Pheggas** [reply]
Ďakujem. Pre hlas som contributoval už do mozilly ale určite pozriem aj tie vety.

**Comment by schizza** [comment]
> Rád by som contributoval čo sa týka slovenčiny napríklad aj takýmto štýlom - podp

**Comment by domasist** [comment]
Ahojte. 

Urobil som male testovanie slovenskych fraz ale whisper vela frazam nerozumel. Akokolvek som sa znazil vyslovovat tak to moc nepomohlo. Rad by som pomohol, aby slovencina bola pouzitelna pre beznych ludi. Mame niekolko instalacii HA u beznych ludi a velmi by ocenili ovladat dom v slovencine.  

Pri testovani v anglictine mi ako najpouzitelnejsie prislo pouzit alias na scene alebo skripte. Jedno slovo napr. SNAKE tak vie otvorit branu, zhasnut, alarmovát a vela vela dalsieho. Je vsak specificke custom riesenie, ktore je nepouzitelne vseobecne, ak hovorim, ze chcem aby whisper porozumel slovu napríklad HAD. No whisper mal problem aj pri porozumeni takehoto slova.

Ak viete cim to je, co by tomu mohlo pomoct a ako, napiste. 
Dakujem.

**Reply by softko** [reply]
Ahoj, whisper nie je dostatocne vytrenovany na SK predpokladam, pretoze snazit sa tam o nieco je naozaj bolestive. SK ovladanie pouzivam len cez telefon (shortcut siri ktora preposle ako text do HA). Priamo v ha bohuzial zatial len EN (teda pokial nechces nejake cloudove riesenie)

**Reply by domasist** [reply]
Ahoj. Určite lokálne riešnie, nie cloud. Ale niečo jednoduchšie pre bežných ľudí a SK. Vedeli by sme slovenčine a jej porozumeniu nejako pomôcť? Aká je šanca, že by sme jednoduché ovládanie na lokálnej úrovni dokázali pomocou whisper rozbehať? V čom je to bolestivé?

**Reply by LubosKadasi** [reply]
Ahoj. V slovenčine nič lokálne použiteľné nepoznám. Niečo som skúšal ale momentálne je to dosť zlé. Používam cloud. Viac nižsie...

**Reply by Pheggas** [reply]
Môžeš pomôcť napr pomocou common voicu: https://commonvoice.mozilla.org/sk 

Nahovoríš vety ktoré sa ti zobrazujú a tie sa následne budú brať pri trénovaní Whisper modelov.

**Reply by domasist** [reply]
> Môžeš pomôcť napr pomocou common voicu: https://commonvoice.mozilla.org/sk
> 
> Nahovoríš vety ktoré sa ti zobrazujú a tie sa následne budú brať pri trénovaní Whisper modelov.

Ano, tomu som uz cas venoval, ale pride mi to pri kapacite SK vstupov ako zbytocny cas, ak potrebujeme aby whisper dokazal pomocou jednoduchyvh SK vstupov ovladat domacnost. Rozumiem potrebe velkeho objemu dat pre ucenie whiper modelov (rozne intonacie, farba hlasu, prostredia a podobne) ale nebolo by jednoduchsie/efektivnejsie urobit tuto mnozinu cisto na vetach potrebnych pre domacnost a jej ovladanie ako take?

**Reply by Pheggas** [reply]
Kto ti niečo také spraví? A navyše zadarmo? Skôr som názoru že keď ľudia na Slovensku začnú používať príkazy ako zapni, vypni, povysávaj atď tak sa začnú pýtať aj zložitejšie otázky (resp budú chcieť sa pýtať), ako napr. Pridať do nákupného zoznamu xyz, Nastav budík v piatok na 8:00 a podobne. 

Myslím si že tvoj prístup je príliš prvoplánový a nemyslíš do budúcna. Je pekné ak spravíš ľahký model pre commandy ako vypnúť, zapnúť a podobne ale ľudia si na to zvyknú a budú chcieť viac (ako vždy). Preto prosím, v mene celej open source komunity, contributuj do existujúcich projektov namiesto vytvárania niečoho nového čo ti časom aj tak nebude stačiť. 

Navnímal som že teda asi máš nejaký biznis pre domovu automatizáciu, tak zapriahni seba, svojich zamestnancov a blízkych aby z toho profitoval každý. Koniec koncov, celý home assistant je open source tak by bolo fajn zachovať tú rovinu.

**Reply by LubosKadasi** [reply]
> ... na vetach potrebnych pre domacnost a jej ovladanie ako take?

Ahoj @domasist.  Je tam možné aj pridávať vety, ktoré budú následne ponúkané na nahovorenie: https://commonvoice.mozilla.org/sk/write

**Reply by jose1711** [reply]
ahoj skús mrknúť na nedávny blogpost na HA: https://www.home-assistant.io/blog/2025/02/13/voice-chapter-9-speech-to-phrase/. speech-to-phrase by mohlo pomôcť, pretože:
* je to rýchle (aj na maline) a malo by sa to dať v pohode bežať aj lokálne
* pri tých pár frázach, čo to rozoznáva by to mohlo byť tiež dostatočne presné

**Reply by jose1711** [reply]
k speech-to-phrase: slovencina nie je podporovana -> chyba natrenovany model.

**Comment by softko** [comment]
Ahojte, 
chcel by som otvorit diskusiu ohladne predloziek. Momentalne sa pouzivaju _v|vo|na|pred|za|pod|pri_ - predlozka "za" mi nedava zmysel. Neviem si predstavit situaciu jej pouzitia. Kedze sa pouziva s oblastou (area) a tym padom sa to nepouzije ako napr. svetlo za domom (jedine ze by area bol dom, ale to by tam potom muselo byt len jedno svetlo v celom dome aby to fungovalo). 
_pred|pod|pri_ sa este nejak da pouzit s oblastou, aj ked mi to pride trochu priohnute, ale zase niekomu to moze prist bezne. Ale ta spominana "za", mi nesedi na pouzitie vobec.
Nechcel som ju mazat len tak, tak sa pytam na nazor.
Diky

**Reply by LubosKadasi** [reply]
Ahoj, asi budeš mať pravdu.

`v|vo|na` je predložka pre slotom `{area}` a `pred|za|pod|pri` už podľa mňa súčasť názvu (slotu) `{area}`
- [v] {obývačke}, [vo] {vchode}, [na] {schodoch}
- {pred vchodom}, {za garážou}, {pod schodami}, {pri dome}

...takže to môžme zmazať. Mohlo by to zjednodušiť/zrýchliť rozpoznávanie.

**Reply by softko** [reply]
ano, presne takto som to myslel

**Comment by domasist** [comment]
@LubosKadasi otázka priamo na pripravovaný vooice hw od NC. V poslednom streame potvrdili,že language lidri dostali možnosť ho testovať. Aké s ním máš skúsenosti?

**Reply by LubosKadasi** [reply]
Ahoj. Vzhľadom na momentálne informačné embargo, snáď do https://www.youtube.com/watch?v=ZgoaoTpIhm8, ti moc prezradiť nemôžem. Každopádne, funkčne je to podobné (ale iné) ako ESP32-S3-BOX-3. 
Môj setup s týmto je skrátene:

> 👄  -> ❓-> STT (HA Cloud) -> Google Generative AI  -> TTS (HA Cloud) -> 👂

![image](https://github.com/user-attachments/assets/fa1f0768-33be-48f2-8fc0-4eff5af06131)

A odpoveď:
1. Funguje to fajn, dá sa s tým pracovať (čisto lokálne som neskúšal).
2. Detiská to majú rady, lebo rozumejú a vie im to aj odpovedať na otázky.

**Reply by domasist** [reply]
Dakujem a chapem to embargo. Rozhodne stream budem sledovat. Paulus hovoril, ze chcu mat tovar dostupny v case oznamenia, len neviem ci tym myslel aj SK. 

Zaujima ma to hlavne pre lokalne riesenie zakladneho ovladania domacnosti v SK jazyku pre beznych ludi. Teda to co 80% domacnosti robi pomocou standardnych vypinacov (svetla, sceny, zaluzie, max hudba predvolene programy). Domnievam sa, ze vacsina narocnejsich veci by mala/mohla byt automatizovana kedy speaker iba oznami zmenu pomocou TTS, ak to bude nutne. 

STT (faster-whisper) mam pustene na servery pre koncove RPI HA instalacie a tu je odozva okamzita. V tvojom nastaveni (vid tvoj screenshot) bezi STT v SK pomocou HA Cloud alebo to vsetko riesi spusteny Google Gen AI 1 agent? Ak to riesi vsetko HA Cloud, v akom stave je rozpoznavanie SK tam?

**Reply by LubosKadasi** [reply]
> V tvojom nastaveni (vid tvoj screenshot) bezi STT v SK pomocou HA Cloud alebo to vsetko riesi spusteny Google Gen AI 1 agent? Ak to riesi vsetko HA Cloud, v akom stave je rozpoznavanie SK tam?

Ahoj. **HA Cloud** v mojom prípade rieši len prevod reči na text a opačne. Má to svoje muchy aj v STT aj TTS ale funguje to najlepšie z toho, čo som skúšal.
**Google Ai** dostane text v slovenčine, čo som povedal (z HA STT Cloud), spracuje ho na vykonateľný intent, ktorému rozumie HA (a HA ho vykoná, ak je to možné) a zároveň sformuluje odpoveď (pre HA TTS Cloud). 

Neviem, či som to napísal zrozumiteľne ale je si to možné zdarma vyskúšať:
https://account.nabucasa.com/signup/
https://www.home-assistant.io/integrations/google_generative_ai_conversation/

Prikladám aj moje nastavenie pre AI.
Pozor max "Top K" google nedávno menil na 40 vrátane!

![image](https://github.com/user-attachments/assets/e8370727-98eb-4431-a5da-3381fa9eda7d)

**Comment by tiimsvk** [comment]
Ahojte viete mi poradiť ako meniť teplotu na termostate? Ďakujem Lebo ak zadam 
```
nastav teplotu termostatu na 22
Jas teplotu termostatu nastavený na 22
```
tak mi meni jas nie teplotu :) Ďakujem 
PS: ak to davam do zleho topicu tak sa ospravedlnujem

**Reply by softko** [reply]
Ahoj, je to tym, ze matchuje iny intent. Co som pozeral ostatne jazyky, tak maju taky isty problem. Je zaujimave, ze ked si to pustis vo vyvojom prostredi (python3 -m script.intentfest parse --language sk --sentence "nastav teplotu na 22") tak to sparsuje ako HassClimateSetTemperature, ale ked priamo v HA cez devloper tool -> assist tak je to HassLightSet.
Ako riesenie je mozne, aspon zatial, si spravit na to automatizaciu kde pouzijes trigger sentence a tam si uz poriesis nastavenie teploty

**Reply by tiimsvk** [reply]
Áno k tomuto som sa už distal ale neviem ako dynamicky meniť nazov climate.name a teplotu 

```
alias: test
description: ""
triggers:
  - trigger: conversation
    command:
      - nastav teplotu {name} na {temperature}
conditions: []
actions:
  - action: climate.set_temperature
    metadata: {}
    data:
     temperature: 25    <----dynamicky
      hvac_mode: heat
    target:
      entity_id: climate.thermostat <----dynamicky
mode: single
```

**Reply by LubosKadasi** [reply]
Ahoj @tiimsvk . Skús takto https://www.home-assistant.io/docs/automation/trigger/#sentence-wildcards

**Reply by softko** [reply]
Ahoj, takto by mohli vyzerat akcie v automatizacii, s tym ze davas nazov termostatu +- podobne by sa to dalo aj keby si hovoril miestnost (area) namiesto nazvu termostatu
```
actions:
  - variables:
      temperature: >-
        {{ trigger.slots.temperature|replace('°','')|replace(',','.')|float(0)
        }}
      entity_id: >-
        {{ (expand(states.climate) | selectattr('attributes.friendly_name',
        'eq', trigger.slots.name) | map(attribute='entity_id') | list)[0] or
        None }}
  - if:
      - condition: template
        value_template: "{{ temperature > 0 and entity_id != None }}"
    then:
      - action: climate.set_temperature
        metadata: {}
        data:
          hvac_mode: heat
          temperature: "{{ temperature }}"
        target:
          entity_id: "{{ entity_id }}"
      - set_conversation_response: >-
          Teplota {{ trigger.slots.name }} nastavena na {{
          trigger.slots.temperature }}
    else:
      - set_conversation_response: "{{ 'neznamy termostat' if temperature > 0 else 'Spatna teplota' }}"
```

**Reply by tiimsvk** [reply]
Chvíľu mi to trvalo pokiaľ som prišiel ako funguje custom_sentence a intent script ale uz to funguje :) 
Ešte otázka:
Je možné v časti lists: ze by som nemusel definovat tu nazov ktory poviem "(termostat|termostate|na termostate|termostatu)" ale aby mi to bralo alias ktory mam definovany v entite?

custom_sentence.yaml:
```
language: sk
intents:
  SetTemperature:
    data:
      - sentences:
          - "nastav teplotu {termostat_name} na {temperature}"
  Set_hvac_mode:
    data:
      - sentences:
          - "nastav {termostat_name} na automatiku"
          
lists:
  termostat_name:
    values:
      - in: "(termostat|termostate|na termostate|termostatu)"
        out: "climate.thermostat"
      - in: "klimatizácia"
        out: "climate.obyvacia_izba_klima"
      - in: "klimatizácia v ateliéry"
        out: "climate.atelier_klima"
```
intent_script.yaml:
```
SetTemperature:
    action:
      - service: "climate.set_temperature"
        data:
          temperature: "{{temperature}}"
          hvac_mode: heat
        target:
          entity_id: "{{termostat_name}}"
    speech:
      text: "Teplota na {{termostat_name}} bola nastavená {{temperature}} stupňou celazia."
Set_hvac_mode:
    action:
      - service: "climate.set_hvac_mode"
        data:
          hvac_mode: auto
        target:
          entity_id: "{{termostat_name}}"
    speech:
      text: "{{termostat_name}} bola nastavený na automatický režim"
```

Samozrejme musim ešte vylepšiť niektoréveci :)

**Comment by tiimsvk** [comment]
Ahojte skúšam zapisovaťvstuné odpovede napríklad pre rádio európu 2 a zatiaľ mám zapís takto:
```
  radio:
    values:
      - in: "(Európu 2|Europu 2|Európa 2|Europa 2|europa2|európa2|E2|rádio|radio|europu2|európu2|europa2|európa2|europu dva|európu dva|európa dva|europa dva|rádio europu dva|rádio europa dva|rádio europu 2|rádio europa 2|rádio európu 2|rádio európu 2|stanicu europu dva|stanicu europa dva|stanicu európu dva|stanicu európa dva)"
        out: media-source://radio_browser/cb61763d-d635-4983-82c1-4a6a1e8ad17b
```
Chcel by som sa opýtať aká je syntaxa týchto zápisov či sa to dá jednoduchšie alebo nie? Pretože často sa opakuje začiatočné písmenka slova a následne sa mení iba koncovka. Druhá otázka ťažšia asi voice assitant nedokáže ignorovať internpukciu ak by som mu to prikázal (dĺžne predovšetkým)
