### ISSUE TITLE
[PL] Invalid states for cover.* entities in _fixtures.yaml

### ISSUE THREAD

**Issue by jose1711** [OHF-Voice/intents#3105]
As per https://www.home-assistant.io/integrations/cover/ "close" is not a supported state for an entity in `cover` domain. Several such entities exist in `tests/pl/_fixtures.yaml`, e. g. :
```
  - name: "Osłon(a|ę)"
    id: "cover.zaluzja"
    area: "dining_id"
    state: "close"
    attributes:
      device_class: shade
```
@Uriziel01 @witold-gren
